
my:
   msg: Hello World
   details: welcome to spring world ${my.msg}
   list: abc,xyz,sfd,erd
   key.value: "{22:'Iron Man',44:'Bat Man',66:'Shakti Man'}"

db:
   name: mysql
   host: 127.0.0.1
   port: 8000

#spring.profiles.active: test

#spring.cloud.config.uri: http://localhost:8088 // this is no longer used
management.endpoints.web.exposure.include: health,info,refresh

spring.config.import=optional:configserver: http://localhost:8888

spring.application.name : spring-config